title: TheRedP4nther
author: TheRedP4nther
description: TheRedP4nther Blog
google_analytics:
google_site_verification_content: 
disqus_forum_shortname: theredp4nther-github-io

#Usernames and badges
htb_badge_no: 1332776
thm_badge_no:
show_thm_htb_badges_in_nav: true
github_username: TheRedP4nther
gitlab:
medium:
stackoverflow:
hacker_news:
linkedin: lois-del-rio-somoza
twitch:
youtube:
twitter: TheRedP4nther
facebook:
instagram: TheRedP4nther
reddit:
pinterest:
telegram:
steam:

markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true
exclude: [
   /*/*/_problems/*,
   scripts
]
plugins:
   - jekyll-seo-tag
   - jemoji
   - jekyll-sitemap
   - jekyll-github-metadata
collections:
   pages:
      output: true
      permalink: /:name
   writeups:
      output: true
   solutions:
      output: true
   blog:
      output: true
